import { motion } from "framer-motion";
import { Section } from "./Section";
import { Github, ArrowUpRight } from "lucide-react";

const projects = [
  {
    title: "FlowForge",
    subtitle: "AI Project Planner",
    description:
      "Web platform where users describe a project idea in natural language and instantly receive an AI-generated flowchart and sequence diagram. Solves the 'where to start' problem with a visual roadmap from idea to execution.",
    stack: ["React.js", "Node.js", "Gemini API", "Mermaid.js"],
    github: "https://github.com/vaibhavkr/flowforge",
  },
  {
    title: "Geo-Trivia",
    subtitle: "Real-time Multiplayer Quiz",
    description:
      "A college capstone project — a geography quiz game where questions are dynamically generated by Gemini AI based on the user's selected location, with real-time multiplayer powered by WebSockets.",
    stack: ["React.js", "Node.js", "WebSocket", "Gemini AI"],
    github: "https://github.com/darshanCommits/geo-trivia",
  },
];

export function Projects() {
  return (
    <Section
      id="projects"
      eyebrow="Projects"
      title="Selected work."
      description="A look at recent things I've built — from AI tools to real-time multiplayer apps."
    >
      <div className="grid md:grid-cols-2 gap-6">
        {projects.map((p, i) => (
          <motion.a
            key={p.title}
            href={p.github}
            target="_blank"
            rel="noreferrer"
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: i * 0.1 }}
            className="group relative p-8 rounded-3xl bg-card border border-border shadow-soft hover:shadow-elegant hover:-translate-y-1 transition-smooth overflow-hidden"
          >
            <div className="absolute -top-20 -right-20 h-40 w-40 rounded-full bg-gradient-primary opacity-10 group-hover:opacity-20 blur-2xl transition-smooth" />

            <div className="flex items-start justify-between mb-4">
              <div>
                <h3 className="text-2xl font-bold mb-1">{p.title}</h3>
                <p className="text-sm text-primary font-medium">{p.subtitle}</p>
              </div>
              <div className="h-10 w-10 rounded-full bg-accent flex items-center justify-center group-hover:bg-gradient-primary transition-smooth">
                <ArrowUpRight className="h-5 w-5 text-accent-foreground group-hover:text-primary-foreground transition-smooth" />
              </div>
            </div>

            <p className="text-muted-foreground text-sm leading-relaxed mb-6">
              {p.description}
            </p>

            <div className="flex flex-wrap gap-2 mb-5">
              {p.stack.map((s) => (
                <span
                  key={s}
                  className="px-2.5 py-1 text-xs rounded-md bg-secondary text-secondary-foreground font-medium"
                >
                  {s}
                </span>
              ))}
            </div>

            <div className="flex items-center gap-1.5 text-sm text-muted-foreground group-hover:text-primary transition-smooth">
              <Github className="h-4 w-4" />
              <span className="font-medium">View on GitHub</span>
            </div>
          </motion.a>
        ))}
      </div>
    </Section>
  );
}
